Add support for logging join, part and quit events
On setting LOG_JOIN, LOG_PART or LOG_QUIT = True, jt-logger.py crashes.

Added messages to the HTML dict to resolve the following KeyError:

      File "jt-logger.py", line 233, in on_join
            if LOG_JOIN:self.format_event("join", event)
      File "jt-logger.py", line 311, in format_event
            msg = STRIPPED(self.format_html[action])
    KeyError: 'join'

Furthermore, if the action was 'quit', then the event.target was None.
Modified the code for reading the channel name from params for the
following case:

      File "jt-logger.py", line 282, in on_quit
            self.format_event("quit", event, {"%chan%" : chan})
      File "jt-logger.py", line 348, in format_event
            self.append_log_msg(date, channel, msg)
      File "jt-logger.py", line 354, in append_log_msg
            log_path = os.path.join(LOG_FOLDER, channel, date) + '.html'
            File "/usr/lib/python2.7/posixpath.py", line 75, in join
            if b.startswith('/'):
    AttributeError: 'NoneType' object has no attribute 'startswith'